<?php

namespace Proj\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleFocusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleFocusRepository extends EntityRepository
{
}
