<?php

namespace Proj\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	// on récupère les X derniers commentaires avec leur article associé
	public function getCommentsWithArticle($limit)
	{
		$qb = $this->createQueryBuilder('c')
			->join('c.article', 'a')
			->addSelect('a');
		if(is_int($limit) && $limit > 0)	
			$qb->setMaxResults($limit);
		
		return $qb
			->getQuery()
			->getResult();
	}
}
