proj_article_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProjArticleBundle:Default:index }

proj_article_articles:
    path:     /articles/{page}
    defaults: { _controller: ProjArticleBundle:Article:index, page: 1}	
    requirements:
        page: \d*	

proj_article_view:
    path:    /article/{id}
    defaults: { _controller: ProjArticleBundle:Article:view }
    requirements:
        id: \d+

proj_article_add:
    path: /article/add
    defaults: { _controller: ProjArticleBundle:Article:add }

proj_article_edit:
    path:    /article/edit/{id}
    defaults: { _controller: ProjArticleBundle:Article:edit }
    requirements:
        id: \d+

proj_article_delete:
    path:    /article/delete/{id}
    defaults: { _controller: ProjArticleBundle:Article:delete }
    requirements:
        id: \d+		